<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://webservice.ifrend.isg.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://webservice.ifrend.isg.com/" name="StockQuoteImplService">
<types>
<xsd:schema>
<xsd:import namespace="http://webservice.ifrend.isg.com/" schemaLocation="http://localhost:9999/ws/hello?xsd=1"/>
</xsd:schema>
</types>
<message name="getQuote">
<part name="parameters" element="tns:getQuote" />
</message>
<message name="getQuoteResponse">
<part name="parameters" element="tns:getQuoteResponse"/>
</message>
<portType name="StockQuote">
<operation name="getQuote">
<input message="tns:getQuote"/>
<output message="tns:getQuoteResponse"/>
</operation>

</portType>
<binding name="StockQuoteImplPortBinding" type="tns:StockQuote">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="getQuote">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
</binding>
<service name="StockQuoteImplService">
<port name="StockQuoteImplPort" binding="tns:StockQuoteImplPortBinding">
<soap:address location="http://localhost:9999/ws/hello"/>
</port>
</service>
</definitions>