CREATE TABLE iloan.ADDRESS 
(
    ID NUMBER(20,0) NOT NULL,
    ADDRESS_ID NUMBER(20,0) NOT NULL,    
    ADDRESSLINE1 VARCHAR2(100 BYTE) DEFAULT NULL,
    ZIPCODE VARCHAR(5 BYTE) DEFAULT NULL,
    HOMEADDRESS VARCHAR(5 BYTE) DEFAULT NULL,
    PERMADDRESS VARCHAR(5 BYTE) DEFAULT NULL,
    TELNUM VARCHAR(20 BYTE) DEFAULT NULL,    
    SUPPID NUMBER(20,0) NOT NULL,
    PERSONALDATAID NUMBER(20,0) NOT NULL,
    JOB_DETAIL_ID NUMBER(20,0) NOT NULL
);


CREATE TABLE iloan.APPLICATION 
(
    ID NUMBER(20,0) NOT NULL,
    APPID NUMBER(20,0) NOT NULL,
    ACCEPTCLASSICCARD VARCHAR(10 BYTE) DEFAULT NULL,
    ACCEPTSAVEANDSWIPE VARCHAR(10 BYTE) DEFAULT NULL,
    APPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CARDTYPECODE VARCHAR(5 BYTE) NULL,
    CARDTYPEDESC VARCHAR(50 BYTE) NULL,
    APPSTATUS NUMBER(2,0) NULL,
    APPSTATUSDESC VARCHAR2(50 BYTE) NULL,
    ENROLLSOS VARCHAR(5 BYTE) NULL
);


CREATE TABLE iloan.CREDITCARD 
(
    ID NUMBER(20,0) NOT NULL,
    APPID NUMBER(20,0) NOT NULL,
    CREDITCARDID NUMBER(20,0) NOT NULL,
    CREDITCARDNUM VARCHAR(20 BYTE) DEFAULT NULL,
    CREDITLIMIT NUMBER(20,0) NULL,
    COMPANY VARCHAR(64 BYTE) DEFAULT NULL,
    MEMBERDATE TIMESTAMP NOT NULL,
    EXISTINGCARD VARCHAR(5 BYTE) NULL,
    OTHERCARD VARCHAR(5 BYTE) NULL
    
);


CREATE TABLE iloan.DOA 
(
    ID NUMBER(20,0) NOT NULL,
    SS_ID NUMBER(20,0) NOT NULL,
    DOA_ID NUMBER(20,0) NOT NULL,
    ISSUANCE VARCHAR(5 BYTE) NULL,
    INCDEC_LIMIT VARCHAR(5 BYTE) NULL,
    INCDEC_LIMIT_VAL VARCHAR2(64 BYTE) NULL,
    CHANGE VARCHAR(5 BYTE) NULL,
    PLEDGE_ACCNT_CODE VARCHAR(5 BYTE) NULL,
    PLEDGE_ACCNT_DESC VARCHAR2(64 BYTE) NULL,
    PLEDGE_ACCNT_NUM VARCHAR2(64 BYTE)  NULL,
    PLEDGE_ACCNT_BRANCH VARCHAR2(64 BYTE)  NULL,
    PLEDGE_AMT_WORDS VARCHAR2(100 BYTE)  NULL,
    PLEDGE_AMT NUMBER(20,0) NULL
);


CREATE TABLE iloan.FUND 
(
    ID NUMBER(20,0) NOT NULL,
    FUNDID NUMBER(20,0) NOT NULL,
    JOB_DETAIL_ID NUMBER(20,0) NOT NULL,
    FUNDCODE VARCHAR(5 BYTE) NOT NULL,
    FUNDDESC VARCHAR2(64 BYTE) NOT NULL
);


CREATE TABLE iloan.INSTRUCTION 
(
    ID NUMBER(20,0) NOT NULL,
    APPID NUMBER(20,0) NOT NULL,
    INSTRUCTION_ID NUMBER(20,0) NOT NULL,
    DELIVERY_PLACE VARCHAR2(100 BYTE) NULL,
    PAYMENTMODE VARCHAR(50 BYTE) NULL,
    ADA_ACCNT_NUM VARCHAR(20 BYTE) NULL,
    ADA_BANK_BRANCH VARCHAR(30 BYTE) NULL,
    MIN_AMOUNT VARCHAR(20 BYTE) NULL,
    MAX_AMOUNT VARCHAR(50 BYTE) NULL
);


CREATE TABLE iloan.JOB_DETAILS 
(
    ID NUMBER(20,0) NOT NULL,
    APPID NUMBER(20,0) NOT NULL,
    JOB_DETAIL_ID NUMBER(20,0) NOT NULL,
    COMPANY VARCHAR2(100 BYTE) NULL,
    OCCUPATION VARCHAR(50 BYTE) NULL,
    WORKNATURE VARCHAR(50 BYTE) NULL,
    ADDRESS_ID NUMBER(20,0) NULL,
    YEARS_EMPLOYED NUMBER(2,0) NULL,
    TOTAL_YRS_WORKING NUMBER(2,0) NULL,
    MONTHLYGROSS NUMBER(10,0) NULL,
    SPOUSE_FAM_NAME VARCHAR(30 BYTE) NULL,
    SPOUSE_MIDD_NAME VARCHAR(30 BYTE) NULL,
    SPOUSE_DOB TIMESTAMP NULL    
);


CREATE TABLE iloan.PERSONALDATA 
(
    ID NUMBER(20,0) NOT NULL,
    APPID NUMBER(20,0) NOT NULL,
    PERSONALDATAID NUMBER(20,0) NOT NULL,
    FAMILYNAME VARCHAR(30 BYTE) NULL,
    GIVENNAME VARCHAR(30 BYTE) NULL,
    MIDDLENAME VARCHAR(30 BYTE) NULL,
    CARDNAME VARCHAR(30 BYTE) NULL,
    BIRTHDATE TIMESTAMP NULL,
    BIRTHPLACE VARCHAR(64 BYTE) NULL,
    CIVILSTATUS VARCHAR(20 BYTE) NULL,
    GENDER VARCHAR(5 BYTE) NULL,
    NATIONALITY VARCHAR(30 BYTE) NULL,
    OTHERNATIONAL VARCHAR(5 BYTE) NULL,
    MOBILENUM VARCHAR(30 BYTE) NULL,
    EMAIL VARCHAR(50 BYTE) NULL,
    MOTHERNAME VARCHAR2(100 BYTE) NULL,
    CHILDREN NUMBER(2,0) NULL,
    HOMEADDRESS NUMBER(20,0) NULL,
    PERMADDRESS NUMBER(20,0) NULL,
    HOMEOWNERSHIP VARCHAR(30 BYTE) NULL,
    LENGTHOFSTAY NUMBER(2,0)  NULL,
    CARS NUMBER(2,0)  NULL,
    CARMODEL VARCHAR(64 BYTE) NULL,
    EDUCATION VARCHAR(64 BYTE) NULL,
    TIN VARCHAR(30 BYTE) NULL,
    SSSNUM VARCHAR(30 BYTE) NULL,
    SSSMEMBER VARCHAR(5 BYTE) NULL,
    GSISMEMBER VARCHAR(5 BYTE) NULL,
    OTHER_ID_CODE VARCHAR(5 BYTE) NULL,
    OTHER_ID_VALUE VARCHAR(64 BYTE) NULL,
    PERSON_REF_NAME VARCHAR(30 BYTE) NULL,
    PERSON_REF_REL VARCHAR(3 BYTE) NULL,
    PERSON_REF_ADDR VARCHAR2(100 BYTE) NULL   
);


CREATE TABLE iloan.SAVEANDSWIPE 
(
    ID NUMBER(20,0) NOT NULL,
    APPID NUMBER(20,0) NOT NULL,
    SS_ID NUMBER(20,0) NOT NULL,
    DEPOSITOR VARCHAR(5 BYTE) NULL,
    ACCNT_NUM VARCHAR(30 BYTE) NULL,
    BRANCH VARCHAR(30 BYTE) NULL,
    ACCEPT_PLEDGE VARCHAR(5 BYTE) NULL,
    DOA_ID NUMBER(20,0) NOT NULL  
   
);


CREATE TABLE iloan.SUPPLEMENTARY 
(
    ID NUMBER(20,0) NOT NULL,
    APPID NUMBER(20,0) NOT NULL,
    SUPPID NUMBER(20,0) NOT NULL,
    FAMILYNAME VARCHAR(30 BYTE) NOT NULL,
    GIVENNAME VARCHAR(30 BYTE) NOT NULL,
    MIDDLENAME VARCHAR(30 BYTE) NOT NULL,
    CARDNAME VARCHAR(30 BYTE) NOT NULL,
    ADDRESS_ID NUMBER(20,0) NULL,
    RELTOPRINC VARCHAR(30 BYTE) NULL,
    NATIONALITY VARCHAR(30 BYTE) NULL,
    OTHERNATIONAL VARCHAR(5 BYTE) NULL,
    BIRTHDATE TIMESTAMP NULL,
    GENDER VARCHAR(5 BYTE) NULL
    
);


ALTER TABLE iloan.CREDITCARD 
  ADD CONSTRAINT Primary Key PRIMARY KEY (
    CREDITCARDID)  ;
ALTER TABLE iloan.APPLICATION 
  ADD CONSTRAINT Primary Key PRIMARY KEY (
    APPID)  ;
ALTER TABLE iloan.PERSONALDATA 
  ADD CONSTRAINT Primary Key PRIMARY KEY (
    PERSONALDATAID)  ;
ALTER TABLE iloan.ADDRESS 
  ADD CONSTRAINT Primary Key PRIMARY KEY (
    ADDRESS_ID)  ;
ALTER TABLE iloan.JOB_DETAILS 
  ADD CONSTRAINT Primary Key PRIMARY KEY (
    JOB_DETAIL_ID)  ;
ALTER TABLE iloan.SUPPLEMENTARY 
  ADD CONSTRAINT Primary Key PRIMARY KEY (
    SUPPID)  ;
ALTER TABLE iloan.INSTRUCTION 
  ADD CONSTRAINT Primary Key PRIMARY KEY (
    INSTRUCTION_ID)  ;
ALTER TABLE iloan.SAVEANDSWIPE 
  ADD CONSTRAINT Primary Key PRIMARY KEY (
    SS_ID)  ;
ALTER TABLE iloan.DOA 
  ADD CONSTRAINT Primary Key PRIMARY KEY (
    SS_ID)  ;
ALTER TABLE iloan.FUND 
  ADD CONSTRAINT Primary Key PRIMARY KEY (
    FUNDID)  ;
ALTER TABLE iloan.CREDITCARD
  ADD 
    FOREIGN KEY (APPID)
      REFERENCES iloan.APPLICATION;

ALTER TABLE iloan.PERSONALDATA
  ADD 
    FOREIGN KEY (APPID)
      REFERENCES iloan.APPLICATION;

ALTER TABLE iloan.ADDRESS
  ADD 
    FOREIGN KEY (SUPPID)
      REFERENCES iloan.SUPPLEMENTARY;

ALTER TABLE iloan.ADDRESS
  ADD 
    FOREIGN KEY (PERSONALDATAID)
      REFERENCES iloan.PERSONALDATA;

ALTER TABLE iloan.ADDRESS
  ADD 
    FOREIGN KEY (JOB_DETAIL_ID)
      REFERENCES iloan.JOB_DETAILS;

ALTER TABLE iloan.JOB_DETAILS
  ADD 
    FOREIGN KEY (APPID)
      REFERENCES iloan.APPLICATION;

ALTER TABLE iloan.SUPPLEMENTARY
  ADD 
    FOREIGN KEY (APPID)
      REFERENCES iloan.APPLICATION;

ALTER TABLE iloan.INSTRUCTION
  ADD 
    FOREIGN KEY (APPID)
      REFERENCES iloan.APPLICATION;

ALTER TABLE iloan.SAVEANDSWIPE
  ADD 
    FOREIGN KEY (SS_ID)
      REFERENCES iloan.DOA;

ALTER TABLE iloan.SAVEANDSWIPE
  ADD 
    FOREIGN KEY (APPID)
      REFERENCES iloan.APPLICATION;
--commit;

